### ISSUE TITLE
文件名大小写问题

### ISSUE THREAD

**Issue by XiuLin** [freedomofme/Netease#2]
Img.java这个文件名首字母建议大写

**Comment by fantasy-wc** [comment]
同意

**Comment by freedomofme** [comment]
很抱歉，一直都没有来处理这个issues。刚刚已经重命名了。
当初这个命名是由于工具直接将JSON格式的数据转换为类导致的。

另外，这个项目初学时候开发的，现在看起来已经各种不严谨和不规范。
后续可能会重构。
