### ISSUE TITLE
图标是在哪里找的

### ISSUE THREAD

**Issue by zeleven** [freedomofme/Netease#3]

**Comment by freedomofme** [comment]
之前使用hierarchy view从网易新闻APP里面导出的。大概是Android4.4的时代吧。
后来Android版本不断升级后，hierarchy view就不能查看他人（非debuggable）的APP了。你需要先root才能导出来。

**Comment by freedomofme** [comment]
额，后来试了下，如果不root真机的话，下载google开发镜像加载到模拟器中，也可以做到。
