### ISSUE TITLE
关于cybergarage的问题

### ISSUE THREAD

**Issue by xzchsia** [freedomofme/Netease#4]
你好，项目下载下来后，使用AS 3.1.2 API27重新构建
引入cybergarage-upnp-core-2.1.1.jar这个包后（从https://github.com/cybergarage/cybergarage-upnp这个里面下载的），Gradle编译成功，运行的时候，提示
Program type already present: org.cybergarage.http.Date
Message{kind=ERROR, text=Program type already present: org.cybergarage.http.Date, sources=[Unknown source file], tool name=Optional.of(D8)}

实际搜索了，没有发现重复的。

请问您是怎么处理关于这个库的引用的。
谢谢

**Comment by freedomofme** [comment]
有段时间没维护了，我晚点看一下。
记得是没有引入这个库。

**Comment by freedomofme** [comment]
你先clean

**Comment by freedomofme** [comment]
嗯，修好了。。的确引用了了一个HTTP.java 的常量类
