### ISSUE TITLE
你好 

### ISSUE THREAD

**Issue by jj89757hhb** [freedomofme/Netease#6]
请问为什么要加上这个判断？
    MyRecyclerView hold = ((ImageViewHolder) holder).mRecyclerView;
            if (hold.getAdapter() != null && hold.getAdapter() instanceof HorizontalImageRecyclerViewAdapter) {
                //单纯设置数据
                Log.i(TAG, "单纯设置数据");
                getPhotosetImageJsonURl((HorizontalImageRecyclerViewAdapter) hold.getAdapter(), jsonString);
            }

**Comment by freedomofme** [comment]
就是在垂直列表中定义了一种格式是  HorizontalImageRecyclerViewAdapter。 这个是作用是 在垂直列表中嵌入水平列表，用来展示多个水平图片。
